# Generated by Django 5.2.4 on 2025-07-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=64)),
                ('bind_time', models.DateTimeField(auto_now_add=True)),
                ('wx_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.wxuser')),
            ],
        ),
    ]
