# Generated by Django 5.2.4 on 2025-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0002_devicebind'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
