# Generated by Django 5.2.4 on 2025-07-10 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=64, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='upload_time',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='DataCollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('calibrating', '校准中'), ('collecting', '采集中'), ('analyzing', '分析中'), ('completed', '已完成'), ('stopped', '已停止')], default='calibrating', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.wxuser')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_delay', models.JSONField()),
                ('energy_ratio', models.FloatField()),
                ('rom_data', models.JSONField()),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wxapp.datacollectionsession')),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wxapp.datacollectionsession'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['session', 'device_code', 'sensor_type'], name='wxapp_senso_session_fa4056_idx'),
        ),
        migrations.AddField(
            model_name='datacollectionsession',
            name='device_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.devicegroup'),
        ),
    ]
