# Generated by Django 5.2.4 on 2025-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0005_alter_analysisresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectionsession',
            name='status',
            field=models.CharField(choices=[('calibrating', '校准中'), ('collecting', '采集中'), ('stopping', '停止中'), ('analyzing', '分析中'), ('completed', '已完成'), ('stopped', '已停止')], default='calibrating', max_length=20, verbose_name='状态'),
        ),
    ]
