# Generated by Django 5.2.4 on 2025-09-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0006_alter_datacollectionsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='esp32_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ESP32采集时间戳'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='服务器时间戳'),
        ),
    ]
